# Generated by Django 2.1.3 on 2018-12-21 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_booksread_reread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booksread',
            name='dateended',
            field=models.DateField(blank=True, null=True),
        ),
    ]
