# Generated by Django 2.1.3 on 2019-02-16 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_auto_20181221_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='booksread',
            name='quitdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
